### PR TITLE
Remove force encryption

### PR DESCRIPTION
**Pull request by W4TCH0UT**
Give users a choice to encrypt or not to encrypt their device.

### CODE REVIEW

**Comment by W4TCH0UT** [comment]
Merge this please.

**Comment by STELIX** [comment]
Please be sure to respect always the author commit.

**Comment by W4TCH0UT** [comment]
I know, but I committed this.

**Comment by TheNameIsNigel** [comment]
This commit is over 7 months old with no activity, and the commuter did not submit this properly. Closing.

**Pull request closed without merging**
